<template>
  <v-container>
    <h1>Terms & Conditions</h1> 
    <p>Updated at 2023-02-19</p> 
    <h2>General Terms</h2>
    <p>
      By accessing and placing an order with immo-bit.com, you confirm that you are in agreement with and bound by the terms of
      service contained in the Terms & Conditions outlined below. These terms apply to the entire website and any email or other type
      of communication between you and immo-bit.com.<br>
      Under no circumstances shall immo-bit.com team be liable for any direct, indirect, special, incidental or consequential damages,
      including, but not limited to, loss of data or profit, arising out of the use, or the inability to use, the materials on this site, even if
      immo-bit.com team or an authorized representative has been advised of the possibility of such damages. If your use of materials
      from this site results in the need for servicing, repair or correction of equipment or data, you assume any costs thereof.
      immo-bit.com will not be responsible for any outcome that may occur during the course of usage of our resources. We reserve
      the rights to change prices and revise the resources usage policy in any moment.
    </p>

    <h2>License</h2> 
      <p>   
        immo-bit.com grants you a revocable, non-exclusive, non-transferable, limited license to download, install and use the website
        strictly in accordance with the terms of this Agreement.
        These Terms & Conditions are a contract between you and immo-bit.com (referred to in these Terms & Conditions as
        "immo-bit.com", "us", "we" or "our"), the provider of the immo-bit.com website and the services accessible from the
        immo-bit.com website (which are collectively referred to in these Terms & Conditions as the "immo-bit.com Service").
        You are agreeing to be bound by these Terms & Conditions. If you do not agree to these Terms & Conditions, please do not use
        the immo-bit.com Service. In these Terms & Conditions, "you" refers both to you as an individual and to the entity you represent.
        If you violate any of these Terms & Conditions, we reserve the right to cancel your account or block access to your account
        without notice.
        Definitions and key terms
        To help explain things as clearly as possible in this Terms & Conditions, every time any of these terms are referenced, are
        strictly defined as: <br>
        ● Cookie: small amount of data generated by a website and saved by your web browser. It is used to identify your browser,
        provide analytics, remember information about you such as your language preference or login information.<br>
        ● Company: when this policy mentions “Company,” “we,” “us,” or “our,” it refers to ImmoBit, N59, Rue 126 villa, Sidi djillali,
        Sidi bel abbès, Algérie that is responsible for your information under this Terms & Conditions.<br>
        ● Country: where immo-bit.com or the owners/founders of immo-bit.com are based, in this case is Algeria.<br>
        ● Device: any internet connected device such as a phone, tablet, computer or any other device that can be used to visit
        immo-bit.com and use the services. <br>
        ● Service: refers to the service provided by immo-bit.com as described in the relative terms (if available) and on this platform.
        ● Third-party service: refers to advertisers, contest sponsors, promotional and marketing partners, and others who provide
        our content or whose products or services we think may interest you. <br>
        ● Website: immo-bit.com."’s" site, which can be accessed via this URL: https://www.immo-bit.com/ <br>
        ● You: a person or entity that is registered with immo-bit.com to use the Services. <br>
      </p>
      <h2>Restrictions</h2> 
      <p> You agree not to, and you will not permit others to: <br>
        ● License, sell, rent, lease, assign, distribute, transmit, host, outsource, disclose or otherwise commercially exploit the
        website or make the platform available to any third party.<br>
        ● Modify, make derivative works of, disassemble, decrypt, reverse compile or reverse engineer any part of the website.<br>
        ● Remove, alter or obscure any proprietary notice (including any notice of copyright or trademark) of immo-bit.com or its
        affiliates, partners, suppliers or the licensors of the website. <br>
        </p>
        <h2>Your Suggestions</h2> 
        <p> Any feedback, comments, ideas, improvements or suggestions (collectively, "Suggestions") provided by you to immo-bit.com
        with respect to the website shall remain the sole and exclusive property of immo-bit.com.
        immo-bit.com shall be free to use, copy, modify, publish, or redistribute the Suggestions for any purpose and in any way without
        any credit or any compensation to you.
        Your Consent
        We've updated our Terms & Conditions to provide you with complete transparency into what is being set when you visit our site
        and how it's being used. By using our website, registering an account, or making a purchase, you hereby consent to our Terms
        & Conditions.</p>
       
        <h2> Links to Other Websites</h2>
        <p> This Terms & Conditions applies only to the Services. The Services may contain links to other websites not operated or
          controlled by immo-bit.com. We are not responsible for the content, accuracy or opinions expressed in such websites, and such
          websites are not investigated, monitored or checked for accuracy or completeness by us. Please remember that when you use
          a link to go from the Services to another website, our Terms & Conditions are no longer in effect. Your browsing and interaction
          on any other website, including those that have a link on our platform, is subject to that website’s own rules and policies. Such
          third parties may use their own cookies or other methods to collect information about you.</p>
          
        <h2>Cookies</h2>  
        <p>immo-bit.com uses "Cookies" to identify the areas of our website that you have visited. A Cookie is a small piece of data stored
          on your computer or mobile device by your web browser. We use Cookies to enhance the performance and functionality of our
          website but are non-essential to their use. However, without these cookies, certain functionality like videos may become
          unavailable or you would be required to enter your login details every time you visit the website as we would not be able to
          remember that you had logged in previously. Most web browsers can be set to disable the use of Cookies. However, if you
          disable Cookies, you may not be able to access functionality on our website correctly or at all. We never place Personally
          Identifiable Information in Cookies.</p>
          
         <h2>Changes To Our Terms & Conditions</h2>
         <p> You acknowledge and agree that "immo-bit.com" may stop (permanently or temporarily) providing the Service (or any
            features within the Service) to you or to users generally at "immo-bit.com" sole discretion, without prior notice to you. You
            may stop using the Service at any time. You do not need to specifically inform immo-bit.com when you stop using the
            Service. You acknowledge and agree that if immo-bit.com disables access to your account, you may be prevented from
            accessing the Service, your account details or any files or other materials which is contained in your account.
            If we decide to change our Terms & Conditions, we will post those changes on this page, and/or update the Terms & Conditions
            modification date below.</p> 
          
          <h2> Modifications to Our website</h2>
          <p> immo-bit.com reserves the right to modify, suspend or discontinue, temporarily or permanently, the website or any service to
          which it connects, with or without notice and without liability to you.</p> 
          <h2> Updates to Our website</h2>
          <p>immo-bit.com may from time to time provide enhancements or improvements to the features/ functionality of the website, which
          may include patches, bug fixes, updates, upgrades and other modifications ("Updates").<br>
          Updates may modify or delete certain features and/or functionalities of the website. You agree that immo-bit.com has no
          obligation to (i) provide any Updates, or (ii) continue to provide or enable any particular features and/or functionalities of the
          website to you. <br>
          You further agree that all Updates will be (i) deemed to constitute an integral part of the website, and (ii) subject to the terms
          and conditions of this Agreement.</p>
          <h2>Third-Party Services</h2>
          <p>We may display, include or make available third-party content (including data, information, applications and other products
            services) or provide links to third-party websites or services ("Third- Party Services"). <br>
            You acknowledge and agree that immo-bit.com shall not be responsible for any Third-Party Services, including their accuracy,
            completeness, timeliness, validity, copyright compliance, legality, decency, quality or any other aspect thereof. immo-bit.com
            does not assume and shall not have any liability or responsibility to you or any other person or entity for any Third-Party
            Services. <br>
            Third-Party Services and links thereto are provided solely as a convenience to you and you access and use them entirely at
            your own risk and subject to such third parties' terms and conditions.</p>
            <h2>Amendments to this Agreement</h2> 
            <p> immo-bit.com reserves the right, at its sole discretion, to modify or replace this Agreement at any time. If a revision is material
              we will provide at least 30 days' notice prior to any new terms taking effect. What constitutes a material change will be
              determined at our sole discretion.
              By continuing to access or use our website after any revisions become effective, you agree to be bound by the revised terms. If
              you do not agree to the new terms, you are no longer authorized to use immo-bit.com.</p>
             
              <h2>Entire Agreement</h2>  
              <p> The Agreement constitutes the entire agreement between you and immo-bit.com regarding your use of the website and
                supersedes all prior and contemporaneous written or oral agreements between you and immo-bit.com.
                You may be subject to additional terms and conditions that apply when you use or purchase other immo-bit.com's services,
                which immo-bit.com will provide to you at the time of such use or purchase.</p>
               
                <h2>Updates to Our Terms</h2> 
                <p>We may change our Service and policies, and we may need to make changes to these Terms so that they accurately reflect our
                Service and policies. Unless otherwise required by law, we will notify you (for example, through our Service) before we make
                changes to these Terms and give you an opportunity to review them before they go into effect. Then, if you continue to use the
                Service, you will be bound by the updated Terms. If you do not want to agree to these or any updated Terms, you can delete
                your account.</p>
            
               <h2>Intellectual Property</h2> 
               <p>The website and its entire contents, features and functionality (including but not limited to all information, software, text,
                displays, images, video and audio, and the design, selection and arrangement thereof), are owned by immo-bit.com, its
                licensors or other providers of such material and are protected by Algeria and international copyright, trademark, patent, trade
                secret and other intellectual property or proprietary rights laws. The material may not be copied, modified, reproduced,
                downloaded or distributed in any way, in whole or in part, without the express prior written permission of immo-bit.com, unless
                and except as is expressly provided in these Terms & Conditions. Any unauthorized use of the material is prohibited.</p>


                <h2> Agreement to Arbitrate</h2>
                <p>This section applies to any dispute EXCEPT IT DOESN’T INCLUDE A DISPUTE RELATING TO CLAIMS FOR INJUNCTIVE
                OR EQUITABLE RELIEF REGARDING THE ENFORCEMENT OR VALIDITY OF YOUR OR immo-bit.com."’s" INTELLECTUAL
                PROPERTY RIGHTS. The term “dispute” means any dispute, action, or other controversy between you and immo-bit.com
                concerning the Services or this agreement, whether in contract, warranty, tort, statute, regulation, ordinance, or any other legal
                or equitable basis. “Dispute” will be given the broadest possible meaning allowable under law.</p> 
                <h2>Notice of Dispute</h2> 
                <p>In the event of a dispute, you or immo-bit.com must give the other a Notice of Dispute, which is a written statement that sets
                forth the name, address, and contact information of the party giving it, the facts giving rise to the dispute, and the relief
                requested. You must send any Notice of Dispute via email to: immobit.business@gmail.com. immo-bit.com will send any Notice
                of Dispute to you by mail to your address if we have it, or otherwise to your email address. You and immo-bit.com will attempt to
                resolve any dispute through informal negotiation within sixty (60) days from the date the Notice of Dispute is sent. After sixty
                (60) days, you or immo-bit.com may commence arbitration.</p> 
                <h2>Binding Arbitration</h2>
                <p>If you and immo-bit.com don’t resolve any dispute by informal negotiation, any other effort to resolve the dispute will be
                conducted exclusively by binding arbitration as described in this section. You are giving up the right to litigate (or participate in
                as a party or class member) all disputes in court before a judge or jury. The dispute shall be settled by binding arbitration in
                accordance with the commercial arbitration rules of the American Arbitration Association. Either party may seek any interim or
                preliminary injunctive relief from any court of competent jurisdiction, as necessary to protect the party’s rights or property
                pending the completion of arbitration. Any and all legal, accounting, and other costs, fees, and expenses incurred by the
                prevailing party shall be borne by the non-prevailing party.</p> 
                <h2>Submissions and Privacy</h2> 
                <p>  In the event that you submit or post any ideas, creative suggestions, designs, photographs, information, advertisements, data or
                proposals, including ideas for new or improved products, services, features, technologies or promotions, you expressly agree
                that such submissions will automatically be treated as non-confidential and non-proprietary and will become the sole property of
                immo-bit.com without any compensation or credit to you whatsoever. immo-bit.com and its affiliates shall have no obligations
                with respect to such submissions or posts and may use the ideas contained in such submissions or posts for any purposes in
                any medium in perpetuity, including, but not limited to, developing, manufacturing, and marketing products and services using
                such ideas. </p>
                <h2>Miscellaneous</h2> 
                <p> If for any reason a court of competent jurisdiction finds any provision or portion of these Terms & Conditions to be
                unenforceable, the remainder of these Terms & Conditions will continue in full force and effect. Any waiver of any provision of
                these Terms & Conditions will be effective only if in writing and signed by an authorized representative of immo-bit.com.
                immo-bit.com will be entitled to injunctive or other equitable relief (without the obligations of posting any bond or surety) in the
                event of any breach or anticipatory breach by you. immo-bit.com operates and controls the immo-bit.com Service from its offices
                in Algeria. The Service is not intended for distribution to or use by any person or entity in any jurisdiction or country where such
                distribution or use would be contrary to law or regulation. Accordingly, those persons who choose to access the immo-bit.com
                Service from other locations do so on their own initiative and are solely responsible for compliance with local laws, if and to the
                extent local laws are applicable. These Terms & Conditions (which include and incorporate the immo-bit.com Privacy Policy)
                contains the entire understanding, and supersedes all prior understandings, between you and immo-bit.com concerning its
                subject matter, and cannot be changed or modified by you. The section headings used in this Agreement are for convenience
                only and will not be given any legal import.</p>
                <h2>Disclaimer</h2> 
                <p> immo-bit.com is not responsible for any content, code or any other imprecision. <br>
                immo-bit.com does not provide warranties or guarantees. <br>
                In no event shall immo-bit.com be liable for any special, direct, indirect, consequential, or incidental damages or any damages
                whatsoever, whether in an action of contract, negligence or other tort, arising out of or in connection with the use of the Service
                or the contents of the Service. The Company reserves the right to make additions, deletions, or modifications to the contents on
                the Service at any time without prior notice. <br>
                The immo-bit.com Service and its contents are provided "as is" and "as available" without any warranty or representations of
                any kind, whether express or implied. immo-bit.com is a distributor and not a publisher of the content supplied by third parties;
                as such, immo-bit.com exercises no editorial control over such content and makes no warranty or representation as to the
                accuracy, reliability or currency of any information, content, service or merchandise provided through or accessible via the
                immo-bit.com Service. Without limiting the foregoing, immo-bit.com specifically disclaims all warranties and representations in
                any content transmitted on or in connection with the immo-bit.com Service or on sites that may appear as links on the
                immo-bit.com Service, or in the products provided as a part of, or otherwise in connection with, the immo-bit.com Service,
                including without limitation any warranties of merchantability, fitness for a particular purpose or non-infringement of third party
                rights. No oral advice or written information given by immo-bit.com or any of its affiliates, employees, officers, directors, agents,
                or the like will create a warranty. Price and availability information is subject to change without notice. Without limiting the
                foregoing, immo-bit.com does not warrant that the immo-bit.com Service will be uninterrupted, uncorrupted, timely, or error-free.</p>
     
        <h2>Contact Us</h2>  
        <p>Don't hesitate to contact us if you have any questions. <br>
      ● Via Email: immobit.business@gmail.com <br>
      ● Via Phone Number: 0673710705</p>
    
  </v-container>
</template>
